spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store_carousel?useSSL=false&characterEncoding=UTF-8
  profiles:
    active: cache

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    lazy-loading-enabled: true
  type-aliases-package: com.ahao.pojo

ribbon:
  eager-load:
    enabled: true
    clients:
      - carousel-service

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50