spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_cart?useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: mq

mybatis-plus:
  type-aliases-package: com.ahao.pojo
  configuration:
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    lazy-loading-enabled: true
ribbon:
  eager-load:
    enabled: true
    clients:
      - cart-server
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
