spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store_admin?useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: cache,mq
  thymeleaf:
    enabled: true
    cache: true
    servlet:
      content-type: text/html
    encoding: UTF-8
    check-template-location: true
    check-template: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eager-load:
    enabled: true
    clients:
      - admin-server
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    auto-mapping-behavior: full
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
feign:
  httpclient:
    max-connections-per-route: 50
    max-connections: 200
    enabled: true
  client:
    default:
    ConnectTime: 10000
    ReadTimeout: 10000
server:
  servlet:
    context-path: /admin

#OSS配置
aliyun:
  oss:
    file:
      # 控制台 - oss - 点击对应桶 - 概览 - 地域节点
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5t82cN3TfofxJywKvoj5
      keysecret: 7cPhJQBMNewuqXXnUiEjpj1l8YeONo
      bucketname: store-b2c
