spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_category?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ahao.pojo
  configuration:
    auto-mapping-behavior: full
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true

ribbon:
  eager-load:
    enabled: true
    clients:
      - category-server
feign:
  httpclient:
    enabled: true
    max-connections-per-route: 50
    max-connections: 200
