spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_product?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: cache  #激活store-common模块的缓存配置

mybatis-plus:
  type-aliases-package: com.ahao.pojo
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  mapper-locations: classpath:mapper/*.xml

ribbon:
  eager-load:
    clients:
      - product-server
    enabled: true

feign:
  httpclient:
    max-connections: 200
    max-connections-per-route: 50
    enabled: true